sudo: required
services:
     - docker
     
before_install:
     - docker build -t nikTomashevskiy/docker-github:v1.0 -f Dockerfile.dev .

script:
     - docker run nikTomashevskiy/docker-github:v1.0 npm run test -- --coverage
